<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Import Project="..\..\build\common.targets" />

  <ItemGroup>
    <ProjectReference Include="..\SMAPI.Tests.ModApiConsumer\SMAPI.Tests.ModApiConsumer.csproj" />
    <ProjectReference Include="..\SMAPI.Tests.ModApiProvider\SMAPI.Tests.ModApiProvider.csproj" />
    <ProjectReference Include="..\SMAPI.Toolkit.CoreInterfaces\SMAPI.Toolkit.CoreInterfaces.csproj" />
    <ProjectReference Include="..\SMAPI.Toolkit\SMAPI.Toolkit.csproj" />
    <ProjectReference Include="..\SMAPI\SMAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Newtonsoft.Json.Schema" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="..\..\build\0Harmony.dll" />
    <Reference Include="Stardew Valley" HintPath="$(GamePath)\Stardew Valley.dll" Private="True" />
    <Reference Include="StardewValley.GameData" HintPath="$(GamePath)\StardewValley.GameData.dll" Private="True" />
    <Reference Include="MonoGame.Framework" HintPath="$(GamePath)\MonoGame.Framework.dll" Private="True" />
    <Reference Include="xTile" HintPath="$(GamePath)\xTile.dll" Private="True" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docs\technical\mod-health-report-schema-v1.json" Link="TestAssets\ModHealthReport\mod-health-report-schema-v1.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\docs\technical\examples\mod-health-report-v1.json" Link="TestAssets\ModHealthReport\mod-health-report-v1.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\docs\technical\examples\mod-health-report-v1.txt" Link="TestAssets\ModHealthReport\mod-health-report-v1.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
</Project>
